// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoutingPolicy_Mode int32

const (
	RoutingPolicy_BEST_AVAILABLE  RoutingPolicy_Mode = 0 // prefer NPU, then GPU, then CPU
	RoutingPolicy_REQUIRE_NPU     RoutingPolicy_Mode = 1 // fail if no NPU device
	RoutingPolicy_PREFER_REMOTE   RoutingPolicy_Mode = 2 // prefer not-self if possible
	RoutingPolicy_FORCE_DEVICE_ID RoutingPolicy_Mode = 3 // require specific device_id
)

// Enum value maps for RoutingPolicy_Mode.
var (
	RoutingPolicy_Mode_name = map[int32]string{
		0: "BEST_AVAILABLE",
		1: "REQUIRE_NPU",
		2: "PREFER_REMOTE",
		3: "FORCE_DEVICE_ID",
	}
	RoutingPolicy_Mode_value = map[string]int32{
		"BEST_AVAILABLE":  0,
		"REQUIRE_NPU":     1,
		"PREFER_REMOTE":   2,
		"FORCE_DEVICE_ID": 3,
	}
)

func (x RoutingPolicy_Mode) Enum() *RoutingPolicy_Mode {
	p := new(RoutingPolicy_Mode)
	*p = x
	return p
}

func (x RoutingPolicy_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingPolicy_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_proto_enumTypes[0].Descriptor()
}

func (RoutingPolicy_Mode) Type() protoreflect.EnumType {
	return &file_orchestrator_proto_enumTypes[0]
}

func (x RoutingPolicy_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingPolicy_Mode.Descriptor instead.
func (RoutingPolicy_Mode) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	SecurityKey   string                 `protobuf:"bytes,2,opt,name=security_key,json=securityKey,proto3" json:"security_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AuthRequest) GetSecurityKey() string {
	if x != nil {
		return x.SecurityKey
	}
	return ""
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	HostName      string                 `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	ConnectedAt   int64                  `protobuf:"varint,3,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *SessionInfo) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *CommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type DeviceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceId) Reset() {
	*x = DeviceId{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceId) ProtoMessage() {}

func (x *DeviceId) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceId.ProtoReflect.Descriptor instead.
func (*DeviceId) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceId) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DeviceInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // stable id generated by device at first run (uuid stored on disk)
	DeviceName       string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"` // "chinmay-mac", "windows-laptop", etc
	Platform         string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`                       // "macos", "windows", "linux", "android"
	Arch             string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`                               // "amd64", "arm64"
	HasCpu           bool                   `protobuf:"varint,5,opt,name=has_cpu,json=hasCpu,proto3" json:"has_cpu,omitempty"`            // always true
	HasGpu           bool                   `protobuf:"varint,6,opt,name=has_gpu,json=hasGpu,proto3" json:"has_gpu,omitempty"`
	HasNpu           bool                   `protobuf:"varint,7,opt,name=has_npu,json=hasNpu,proto3" json:"has_npu,omitempty"`                                 // false for now, will be true on Snapdragon later
	GrpcAddr         string                 `protobuf:"bytes,8,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`                            // where this device can be reached, e.g. "10.0.0.5:50051"
	CanScreenCapture bool                   `protobuf:"varint,9,opt,name=can_screen_capture,json=canScreenCapture,proto3" json:"can_screen_capture,omitempty"` // true if device can capture screen (tested at startup)
	HttpAddr         string                 `protobuf:"bytes,10,opt,name=http_addr,json=httpAddr,proto3" json:"http_addr,omitempty"`                           // bulk HTTP server address, e.g. "10.0.0.5:8081"
	// LLM inference throughput (for cost estimation)
	LlmPrefillToksPerS float64 `protobuf:"fixed64,11,opt,name=llm_prefill_toks_per_s,json=llmPrefillToksPerS,proto3" json:"llm_prefill_toks_per_s,omitempty"` // 0 = use platform default
	LlmDecodeToksPerS  float64 `protobuf:"fixed64,12,opt,name=llm_decode_toks_per_s,json=llmDecodeToksPerS,proto3" json:"llm_decode_toks_per_s,omitempty"`    // 0 = use platform default
	RamFreeMb          uint64  `protobuf:"varint,13,opt,name=ram_free_mb,json=ramFreeMb,proto3" json:"ram_free_mb,omitempty"`                                 // free RAM in MB (0 = unknown)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *DeviceInfo) GetHasCpu() bool {
	if x != nil {
		return x.HasCpu
	}
	return false
}

func (x *DeviceInfo) GetHasGpu() bool {
	if x != nil {
		return x.HasGpu
	}
	return false
}

func (x *DeviceInfo) GetHasNpu() bool {
	if x != nil {
		return x.HasNpu
	}
	return false
}

func (x *DeviceInfo) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *DeviceInfo) GetCanScreenCapture() bool {
	if x != nil {
		return x.CanScreenCapture
	}
	return false
}

func (x *DeviceInfo) GetHttpAddr() string {
	if x != nil {
		return x.HttpAddr
	}
	return ""
}

func (x *DeviceInfo) GetLlmPrefillToksPerS() float64 {
	if x != nil {
		return x.LlmPrefillToksPerS
	}
	return 0
}

func (x *DeviceInfo) GetLlmDecodeToksPerS() float64 {
	if x != nil {
		return x.LlmDecodeToksPerS
	}
	return 0
}

func (x *DeviceInfo) GetRamFreeMb() uint64 {
	if x != nil {
		return x.RamFreeMb
	}
	return 0
}

type DeviceAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RegisteredAt  int64                  `protobuf:"varint,2,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceAck) Reset() {
	*x = DeviceAck{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAck) ProtoMessage() {}

func (x *DeviceAck) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAck.ProtoReflect.Descriptor instead.
func (*DeviceAck) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeviceAck) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

type DeviceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastSeen      int64                  `protobuf:"varint,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // unix seconds
	CpuLoad       float64                `protobuf:"fixed64,3,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`   // 0..1, or -1 if unavailable
	MemUsedMb     uint64                 `protobuf:"varint,4,opt,name=mem_used_mb,json=memUsedMb,proto3" json:"mem_used_mb,omitempty"`
	MemTotalMb    uint64                 `protobuf:"varint,5,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatus) Reset() {
	*x = DeviceStatus{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatus) ProtoMessage() {}

func (x *DeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatus.ProtoReflect.Descriptor instead.
func (*DeviceStatus) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceStatus) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *DeviceStatus) GetCpuLoad() float64 {
	if x != nil {
		return x.CpuLoad
	}
	return 0
}

func (x *DeviceStatus) GetMemUsedMb() uint64 {
	if x != nil {
		return x.MemUsedMb
	}
	return 0
}

func (x *DeviceStatus) GetMemTotalMb() uint64 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type AITaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`   // "summarize", "transcribe", "analyze_screen"
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"` // for now, just raw text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AITaskRequest) Reset() {
	*x = AITaskRequest{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AITaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AITaskRequest) ProtoMessage() {}

func (x *AITaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AITaskRequest.ProtoReflect.Descriptor instead.
func (*AITaskRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *AITaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AITaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *AITaskRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type AITaskResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SelectedDeviceId   string                 `protobuf:"bytes,1,opt,name=selected_device_id,json=selectedDeviceId,proto3" json:"selected_device_id,omitempty"`
	SelectedDeviceAddr string                 `protobuf:"bytes,2,opt,name=selected_device_addr,json=selectedDeviceAddr,proto3" json:"selected_device_addr,omitempty"`
	WouldUseNpu        bool                   `protobuf:"varint,3,opt,name=would_use_npu,json=wouldUseNpu,proto3" json:"would_use_npu,omitempty"`
	Result             string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"` // stub result: "ROUTED: <task> to <device_name>"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AITaskResponse) Reset() {
	*x = AITaskResponse{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AITaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AITaskResponse) ProtoMessage() {}

func (x *AITaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AITaskResponse.ProtoReflect.Descriptor instead.
func (*AITaskResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *AITaskResponse) GetSelectedDeviceId() string {
	if x != nil {
		return x.SelectedDeviceId
	}
	return ""
}

func (x *AITaskResponse) GetSelectedDeviceAddr() string {
	if x != nil {
		return x.SelectedDeviceAddr
	}
	return ""
}

func (x *AITaskResponse) GetWouldUseNpu() bool {
	if x != nil {
		return x.WouldUseNpu
	}
	return false
}

func (x *AITaskResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`        // server's device ID (may be empty if not configured)
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // unix seconds
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                          // "ok"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *HealthStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HealthStatus) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RoutingPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          RoutingPolicy_Mode     `protobuf:"varint,1,opt,name=mode,proto3,enum=edgemesh.RoutingPolicy_Mode" json:"mode,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // used if FORCE_DEVICE_ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingPolicy) Reset() {
	*x = RoutingPolicy{}
	mi := &file_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingPolicy) ProtoMessage() {}

func (x *RoutingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingPolicy.ProtoReflect.Descriptor instead.
func (*RoutingPolicy) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *RoutingPolicy) GetMode() RoutingPolicy_Mode {
	if x != nil {
		return x.Mode
	}
	return RoutingPolicy_BEST_AVAILABLE
}

func (x *RoutingPolicy) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RoutedCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Policy        *RoutingPolicy         `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutedCommandRequest) Reset() {
	*x = RoutedCommandRequest{}
	mi := &file_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutedCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutedCommandRequest) ProtoMessage() {}

func (x *RoutedCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutedCommandRequest.ProtoReflect.Descriptor instead.
func (*RoutedCommandRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *RoutedCommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoutedCommandRequest) GetPolicy() *RoutingPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *RoutedCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RoutedCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type RoutedCommandResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Output             *CommandResponse       `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	SelectedDeviceId   string                 `protobuf:"bytes,2,opt,name=selected_device_id,json=selectedDeviceId,proto3" json:"selected_device_id,omitempty"`
	SelectedDeviceName string                 `protobuf:"bytes,3,opt,name=selected_device_name,json=selectedDeviceName,proto3" json:"selected_device_name,omitempty"`
	SelectedDeviceAddr string                 `protobuf:"bytes,4,opt,name=selected_device_addr,json=selectedDeviceAddr,proto3" json:"selected_device_addr,omitempty"`
	TotalTimeMs        float64                `protobuf:"fixed64,5,opt,name=total_time_ms,json=totalTimeMs,proto3" json:"total_time_ms,omitempty"`          // includes forwarding overhead
	ExecutedLocally    bool                   `protobuf:"varint,6,opt,name=executed_locally,json=executedLocally,proto3" json:"executed_locally,omitempty"` // true if ran on the coordinator itself
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RoutedCommandResponse) Reset() {
	*x = RoutedCommandResponse{}
	mi := &file_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutedCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutedCommandResponse) ProtoMessage() {}

func (x *RoutedCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutedCommandResponse.ProtoReflect.Descriptor instead.
func (*RoutedCommandResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *RoutedCommandResponse) GetOutput() *CommandResponse {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *RoutedCommandResponse) GetSelectedDeviceId() string {
	if x != nil {
		return x.SelectedDeviceId
	}
	return ""
}

func (x *RoutedCommandResponse) GetSelectedDeviceName() string {
	if x != nil {
		return x.SelectedDeviceName
	}
	return ""
}

func (x *RoutedCommandResponse) GetSelectedDeviceAddr() string {
	if x != nil {
		return x.SelectedDeviceAddr
	}
	return ""
}

func (x *RoutedCommandResponse) GetTotalTimeMs() float64 {
	if x != nil {
		return x.TotalTimeMs
	}
	return 0
}

func (x *RoutedCommandResponse) GetExecutedLocally() bool {
	if x != nil {
		return x.ExecutedLocally
	}
	return false
}

type JobId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobId) Reset() {
	*x = JobId{}
	mi := &file_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobId) ProtoMessage() {}

func (x *JobId) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobId.ProtoReflect.Descriptor instead.
func (*JobId) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *JobId) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                // user request description
	MaxWorkers    int32                  `protobuf:"varint,3,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"` // 0 = use all available devices
	Plan          *Plan                  `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`                                // optional: explicit execution plan
	Reduce        *ReduceSpec            `protobuf:"bytes,5,opt,name=reduce,proto3" json:"reduce,omitempty"`                            // optional: how to combine results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *JobRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JobRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *JobRequest) GetMaxWorkers() int32 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

func (x *JobRequest) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *JobRequest) GetReduce() *ReduceSpec {
	if x != nil {
		return x.Reduce
	}
	return nil
}

// Planning structures
type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*TaskGroup           `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"` // groups execute sequentially
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{19}
}

func (x *Plan) GetGroups() []*TaskGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type TaskGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // execution order (0 = first)
	Tasks         []*TaskSpec            `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`  // tasks in group run in parallel
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskGroup) Reset() {
	*x = TaskGroup{}
	mi := &file_orchestrator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskGroup) ProtoMessage() {}

func (x *TaskGroup) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskGroup.ProtoReflect.Descriptor instead.
func (*TaskGroup) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{20}
}

func (x *TaskGroup) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TaskGroup) GetTasks() []*TaskSpec {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Kind           string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "SYSINFO", "ECHO", "LLM_GENERATE", etc.
	Input          string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	TargetDeviceId string                 `protobuf:"bytes,4,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"` // empty = let orchestrator assign
	// LLM_GENERATE parameters (for cost estimation)
	PromptTokens    int32 `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`            // estimated prompt tokens
	MaxOutputTokens int32 `protobuf:"varint,6,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"` // max output tokens to generate
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_orchestrator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{21}
}

func (x *TaskSpec) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TaskSpec) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TaskSpec) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

func (x *TaskSpec) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TaskSpec) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

type ReduceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // "CONCAT" for now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceSpec) Reset() {
	*x = ReduceSpec{}
	mi := &file_orchestrator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceSpec) ProtoMessage() {}

func (x *ReduceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceSpec.ProtoReflect.Descriptor instead.
func (*ReduceSpec) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{22}
}

func (x *ReduceSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"` // e.g. "distributed to N devices"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_orchestrator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{23}
}

func (x *JobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *JobInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type JobStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // QUEUED, RUNNING, DONE, FAILED
	Tasks         []*TaskStatus          `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	FinalResult   string                 `protobuf:"bytes,4,opt,name=final_result,json=finalResult,proto3" json:"final_result,omitempty"`     // concatenated results when DONE
	CurrentGroup  int32                  `protobuf:"varint,5,opt,name=current_group,json=currentGroup,proto3" json:"current_group,omitempty"` // which group is currently executing
	TotalGroups   int32                  `protobuf:"varint,6,opt,name=total_groups,json=totalGroups,proto3" json:"total_groups,omitempty"`    // total number of groups in plan
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_orchestrator_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{24}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JobStatus) GetTasks() []*TaskStatus {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *JobStatus) GetFinalResult() string {
	if x != nil {
		return x.FinalResult
	}
	return ""
}

func (x *JobStatus) GetCurrentGroup() int32 {
	if x != nil {
		return x.CurrentGroup
	}
	return 0
}

func (x *JobStatus) GetTotalGroups() int32 {
	if x != nil {
		return x.TotalGroups
	}
	return 0
}

type TaskStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AssignedDeviceId   string                 `protobuf:"bytes,2,opt,name=assigned_device_id,json=assignedDeviceId,proto3" json:"assigned_device_id,omitempty"`
	AssignedDeviceName string                 `protobuf:"bytes,3,opt,name=assigned_device_name,json=assignedDeviceName,proto3" json:"assigned_device_name,omitempty"`
	State              string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"` // QUEUED, RUNNING, DONE, FAILED
	Result             string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Error              string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_orchestrator_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{25}
}

func (x *TaskStatus) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatus) GetAssignedDeviceId() string {
	if x != nil {
		return x.AssignedDeviceId
	}
	return ""
}

func (x *TaskStatus) GetAssignedDeviceName() string {
	if x != nil {
		return x.AssignedDeviceName
	}
	return ""
}

func (x *TaskStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskStatus) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TaskStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // "ECHO" or "SYSINFO"
	Input         string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_orchestrator_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{26}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TaskRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	TimeMs        float64                `protobuf:"fixed64,5,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_orchestrator_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{27}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetTimeMs() float64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

type WebRTCConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetFps     int32                  `protobuf:"varint,2,opt,name=target_fps,json=targetFps,proto3" json:"target_fps,omitempty"`          // default 8 if 0
	JpegQuality   int32                  `protobuf:"varint,3,opt,name=jpeg_quality,json=jpegQuality,proto3" json:"jpeg_quality,omitempty"`    // default 60 if 0
	MonitorIndex  int32                  `protobuf:"varint,4,opt,name=monitor_index,json=monitorIndex,proto3" json:"monitor_index,omitempty"` // default 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCConfig) Reset() {
	*x = WebRTCConfig{}
	mi := &file_orchestrator_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCConfig) ProtoMessage() {}

func (x *WebRTCConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCConfig.ProtoReflect.Descriptor instead.
func (*WebRTCConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{28}
}

func (x *WebRTCConfig) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WebRTCConfig) GetTargetFps() int32 {
	if x != nil {
		return x.TargetFps
	}
	return 0
}

func (x *WebRTCConfig) GetJpegQuality() int32 {
	if x != nil {
		return x.JpegQuality
	}
	return 0
}

func (x *WebRTCConfig) GetMonitorIndex() int32 {
	if x != nil {
		return x.MonitorIndex
	}
	return 0
}

type WebRTCOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Sdp           string                 `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"` // offer SDP including ICE candidates (non-trickle)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCOffer) Reset() {
	*x = WebRTCOffer{}
	mi := &file_orchestrator_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCOffer) ProtoMessage() {}

func (x *WebRTCOffer) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCOffer.ProtoReflect.Descriptor instead.
func (*WebRTCOffer) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{29}
}

func (x *WebRTCOffer) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *WebRTCOffer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type WebRTCAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Sdp           string                 `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"` // answer SDP including ICE candidates (non-trickle)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCAnswer) Reset() {
	*x = WebRTCAnswer{}
	mi := &file_orchestrator_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCAnswer) ProtoMessage() {}

func (x *WebRTCAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCAnswer.ProtoReflect.Descriptor instead.
func (*WebRTCAnswer) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{30}
}

func (x *WebRTCAnswer) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *WebRTCAnswer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type WebRTCStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCStop) Reset() {
	*x = WebRTCStop{}
	mi := &file_orchestrator_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCStop) ProtoMessage() {}

func (x *WebRTCStop) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCStop.ProtoReflect.Descriptor instead.
func (*WebRTCStop) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{31}
}

func (x *WebRTCStop) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type PlanPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	MaxWorkers    int32                  `protobuf:"varint,3,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanPreviewRequest) Reset() {
	*x = PlanPreviewRequest{}
	mi := &file_orchestrator_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanPreviewRequest) ProtoMessage() {}

func (x *PlanPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanPreviewRequest.ProtoReflect.Descriptor instead.
func (*PlanPreviewRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{32}
}

func (x *PlanPreviewRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlanPreviewRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PlanPreviewRequest) GetMaxWorkers() int32 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

type PlanPreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedAi        bool                   `protobuf:"varint,1,opt,name=used_ai,json=usedAi,proto3" json:"used_ai,omitempty"`
	Notes         string                 `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	Rationale     string                 `protobuf:"bytes,3,opt,name=rationale,proto3" json:"rationale,omitempty"`
	Plan          *Plan                  `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	Reduce        *ReduceSpec            `protobuf:"bytes,5,opt,name=reduce,proto3" json:"reduce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanPreviewResponse) Reset() {
	*x = PlanPreviewResponse{}
	mi := &file_orchestrator_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanPreviewResponse) ProtoMessage() {}

func (x *PlanPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanPreviewResponse.ProtoReflect.Descriptor instead.
func (*PlanPreviewResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{33}
}

func (x *PlanPreviewResponse) GetUsedAi() bool {
	if x != nil {
		return x.UsedAi
	}
	return false
}

func (x *PlanPreviewResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *PlanPreviewResponse) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *PlanPreviewResponse) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *PlanPreviewResponse) GetReduce() *ReduceSpec {
	if x != nil {
		return x.Reduce
	}
	return nil
}

type PlanCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Plan          *Plan                  `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`                            // plan to estimate
	DeviceIds     []string               `protobuf:"bytes,3,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"` // optional: limit to these devices (empty = all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanCostRequest) Reset() {
	*x = PlanCostRequest{}
	mi := &file_orchestrator_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanCostRequest) ProtoMessage() {}

func (x *PlanCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanCostRequest.ProtoReflect.Descriptor instead.
func (*PlanCostRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{34}
}

func (x *PlanCostRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlanCostRequest) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *PlanCostRequest) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

type PlanCostResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalPredictedMs      float64                `protobuf:"fixed64,1,opt,name=total_predicted_ms,json=totalPredictedMs,proto3" json:"total_predicted_ms,omitempty"` // best device's total latency
	DeviceCosts           []*DeviceCostEstimate  `protobuf:"bytes,2,rep,name=device_costs,json=deviceCosts,proto3" json:"device_costs,omitempty"`
	RecommendedDeviceId   string                 `protobuf:"bytes,3,opt,name=recommended_device_id,json=recommendedDeviceId,proto3" json:"recommended_device_id,omitempty"`
	RecommendedDeviceName string                 `protobuf:"bytes,4,opt,name=recommended_device_name,json=recommendedDeviceName,proto3" json:"recommended_device_name,omitempty"`
	HasUnknownCosts       bool                   `protobuf:"varint,5,opt,name=has_unknown_costs,json=hasUnknownCosts,proto3" json:"has_unknown_costs,omitempty"` // true if any step had unknown cost
	Warning               string                 `protobuf:"bytes,6,opt,name=warning,proto3" json:"warning,omitempty"`                                           // warning message if applicable
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlanCostResponse) Reset() {
	*x = PlanCostResponse{}
	mi := &file_orchestrator_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanCostResponse) ProtoMessage() {}

func (x *PlanCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanCostResponse.ProtoReflect.Descriptor instead.
func (*PlanCostResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{35}
}

func (x *PlanCostResponse) GetTotalPredictedMs() float64 {
	if x != nil {
		return x.TotalPredictedMs
	}
	return 0
}

func (x *PlanCostResponse) GetDeviceCosts() []*DeviceCostEstimate {
	if x != nil {
		return x.DeviceCosts
	}
	return nil
}

func (x *PlanCostResponse) GetRecommendedDeviceId() string {
	if x != nil {
		return x.RecommendedDeviceId
	}
	return ""
}

func (x *PlanCostResponse) GetRecommendedDeviceName() string {
	if x != nil {
		return x.RecommendedDeviceName
	}
	return ""
}

func (x *PlanCostResponse) GetHasUnknownCosts() bool {
	if x != nil {
		return x.HasUnknownCosts
	}
	return false
}

func (x *PlanCostResponse) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

type DeviceCostEstimate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeviceId           string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName         string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	TotalMs            float64                `protobuf:"fixed64,3,opt,name=total_ms,json=totalMs,proto3" json:"total_ms,omitempty"`
	StepCosts          []*StepCostEstimate    `protobuf:"bytes,4,rep,name=step_costs,json=stepCosts,proto3" json:"step_costs,omitempty"`
	EstimatedPeakRamMb uint64                 `protobuf:"varint,5,opt,name=estimated_peak_ram_mb,json=estimatedPeakRamMb,proto3" json:"estimated_peak_ram_mb,omitempty"`
	RamSufficient      bool                   `protobuf:"varint,6,opt,name=ram_sufficient,json=ramSufficient,proto3" json:"ram_sufficient,omitempty"` // false if estimated RAM > device free RAM
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeviceCostEstimate) Reset() {
	*x = DeviceCostEstimate{}
	mi := &file_orchestrator_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCostEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCostEstimate) ProtoMessage() {}

func (x *DeviceCostEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCostEstimate.ProtoReflect.Descriptor instead.
func (*DeviceCostEstimate) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{36}
}

func (x *DeviceCostEstimate) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceCostEstimate) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceCostEstimate) GetTotalMs() float64 {
	if x != nil {
		return x.TotalMs
	}
	return 0
}

func (x *DeviceCostEstimate) GetStepCosts() []*StepCostEstimate {
	if x != nil {
		return x.StepCosts
	}
	return nil
}

func (x *DeviceCostEstimate) GetEstimatedPeakRamMb() uint64 {
	if x != nil {
		return x.EstimatedPeakRamMb
	}
	return 0
}

func (x *DeviceCostEstimate) GetRamSufficient() bool {
	if x != nil {
		return x.RamSufficient
	}
	return false
}

type StepCostEstimate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Kind              string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	PredictedMs       float64                `protobuf:"fixed64,3,opt,name=predicted_ms,json=predictedMs,proto3" json:"predicted_ms,omitempty"`
	PredictedMemoryMb float64                `protobuf:"fixed64,4,opt,name=predicted_memory_mb,json=predictedMemoryMb,proto3" json:"predicted_memory_mb,omitempty"`
	UnknownCost       bool                   `protobuf:"varint,5,opt,name=unknown_cost,json=unknownCost,proto3" json:"unknown_cost,omitempty"` // true if step type not recognized
	Notes             string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`                                 // e.g., "using default prefill TPS"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StepCostEstimate) Reset() {
	*x = StepCostEstimate{}
	mi := &file_orchestrator_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepCostEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepCostEstimate) ProtoMessage() {}

func (x *StepCostEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepCostEstimate.ProtoReflect.Descriptor instead.
func (*StepCostEstimate) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{37}
}

func (x *StepCostEstimate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StepCostEstimate) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StepCostEstimate) GetPredictedMs() float64 {
	if x != nil {
		return x.PredictedMs
	}
	return 0
}

func (x *StepCostEstimate) GetPredictedMemoryMb() float64 {
	if x != nil {
		return x.PredictedMemoryMb
	}
	return 0
}

func (x *StepCostEstimate) GetUnknownCost() bool {
	if x != nil {
		return x.UnknownCost
	}
	return false
}

func (x *StepCostEstimate) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type DownloadTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // relative path under shared root, e.g. "test.txt"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTicketRequest) Reset() {
	*x = DownloadTicketRequest{}
	mi := &file_orchestrator_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTicketRequest) ProtoMessage() {}

func (x *DownloadTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTicketRequest.ProtoReflect.Descriptor instead.
func (*DownloadTicketRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{38}
}

func (x *DownloadTicketRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                         // one-time-use download token
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                                   // basename of the file
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`               // file size
	ExpiresUnixMs int64                  `protobuf:"varint,4,opt,name=expires_unix_ms,json=expiresUnixMs,proto3" json:"expires_unix_ms,omitempty"` // absolute expiry (ms since epoch)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTicketResponse) Reset() {
	*x = DownloadTicketResponse{}
	mi := &file_orchestrator_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTicketResponse) ProtoMessage() {}

func (x *DownloadTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTicketResponse.ProtoReflect.Descriptor instead.
func (*DownloadTicketResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{39}
}

func (x *DownloadTicketResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DownloadTicketResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DownloadTicketResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DownloadTicketResponse) GetExpiresUnixMs() int64 {
	if x != nil {
		return x.ExpiresUnixMs
	}
	return 0
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\bedgemesh\"\a\n" +
	"\x05Empty\"Q\n" +
	"\vAuthRequest\x12\x1f\n" +
	"\vdevice_name\x18\x01 \x01(\tR\n" +
	"deviceName\x12!\n" +
	"\fsecurity_key\x18\x02 \x01(\tR\vsecurityKey\"l\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12!\n" +
	"\fconnected_at\x18\x03 \x01(\x03R\vconnectedAt\"]\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\"^\n" +
	"\x0fCommandResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\"'\n" +
	"\bDeviceId\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\xb3\x03\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x17\n" +
	"\ahas_cpu\x18\x05 \x01(\bR\x06hasCpu\x12\x17\n" +
	"\ahas_gpu\x18\x06 \x01(\bR\x06hasGpu\x12\x17\n" +
	"\ahas_npu\x18\a \x01(\bR\x06hasNpu\x12\x1b\n" +
	"\tgrpc_addr\x18\b \x01(\tR\bgrpcAddr\x12,\n" +
	"\x12can_screen_capture\x18\t \x01(\bR\x10canScreenCapture\x12\x1b\n" +
	"\thttp_addr\x18\n" +
	" \x01(\tR\bhttpAddr\x122\n" +
	"\x16llm_prefill_toks_per_s\x18\v \x01(\x01R\x12llmPrefillToksPerS\x120\n" +
	"\x15llm_decode_toks_per_s\x18\f \x01(\x01R\x11llmDecodeToksPerS\x12\x1e\n" +
	"\vram_free_mb\x18\r \x01(\x04R\tramFreeMb\"@\n" +
	"\tDeviceAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\rregistered_at\x18\x02 \x01(\x03R\fregisteredAt\"\xa5\x01\n" +
	"\fDeviceStatus\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tlast_seen\x18\x02 \x01(\x03R\blastSeen\x12\x19\n" +
	"\bcpu_load\x18\x03 \x01(\x01R\acpuLoad\x12\x1e\n" +
	"\vmem_used_mb\x18\x04 \x01(\x04R\tmemUsedMb\x12 \n" +
	"\fmem_total_mb\x18\x05 \x01(\x04R\n" +
	"memTotalMb\"\x14\n" +
	"\x12ListDevicesRequest\"E\n" +
	"\x13ListDevicesResponse\x12.\n" +
	"\adevices\x18\x01 \x03(\v2\x14.edgemesh.DeviceInfoR\adevices\"X\n" +
	"\rAITaskRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"\xac\x01\n" +
	"\x0eAITaskResponse\x12,\n" +
	"\x12selected_device_id\x18\x01 \x01(\tR\x10selectedDeviceId\x120\n" +
	"\x14selected_device_addr\x18\x02 \x01(\tR\x12selectedDeviceAddr\x12\"\n" +
	"\rwould_use_npu\x18\x03 \x01(\bR\vwouldUseNpu\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\"f\n" +
	"\fHealthStatus\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb3\x01\n" +
	"\rRoutingPolicy\x120\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1c.edgemesh.RoutingPolicy.ModeR\x04mode\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"S\n" +
	"\x04Mode\x12\x12\n" +
	"\x0eBEST_AVAILABLE\x10\x00\x12\x0f\n" +
	"\vREQUIRE_NPU\x10\x01\x12\x11\n" +
	"\rPREFER_REMOTE\x10\x02\x12\x13\n" +
	"\x0fFORCE_DEVICE_ID\x10\x03\"\x94\x01\n" +
	"\x14RoutedCommandRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12/\n" +
	"\x06policy\x18\x02 \x01(\v2\x17.edgemesh.RoutingPolicyR\x06policy\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\"\xab\x02\n" +
	"\x15RoutedCommandResponse\x121\n" +
	"\x06output\x18\x01 \x01(\v2\x19.edgemesh.CommandResponseR\x06output\x12,\n" +
	"\x12selected_device_id\x18\x02 \x01(\tR\x10selectedDeviceId\x120\n" +
	"\x14selected_device_name\x18\x03 \x01(\tR\x12selectedDeviceName\x120\n" +
	"\x14selected_device_addr\x18\x04 \x01(\tR\x12selectedDeviceAddr\x12\"\n" +
	"\rtotal_time_ms\x18\x05 \x01(\x01R\vtotalTimeMs\x12)\n" +
	"\x10executed_locally\x18\x06 \x01(\bR\x0fexecutedLocally\"\x1e\n" +
	"\x05JobId\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xb2\x01\n" +
	"\n" +
	"JobRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1f\n" +
	"\vmax_workers\x18\x03 \x01(\x05R\n" +
	"maxWorkers\x12\"\n" +
	"\x04plan\x18\x04 \x01(\v2\x0e.edgemesh.PlanR\x04plan\x12,\n" +
	"\x06reduce\x18\x05 \x01(\v2\x14.edgemesh.ReduceSpecR\x06reduce\"3\n" +
	"\x04Plan\x12+\n" +
	"\x06groups\x18\x01 \x03(\v2\x13.edgemesh.TaskGroupR\x06groups\"K\n" +
	"\tTaskGroup\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12(\n" +
	"\x05tasks\x18\x02 \x03(\v2\x12.edgemesh.TaskSpecR\x05tasks\"\xc8\x01\n" +
	"\bTaskSpec\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12(\n" +
	"\x10target_device_id\x18\x04 \x01(\tR\x0etargetDeviceId\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x05R\fpromptTokens\x12*\n" +
	"\x11max_output_tokens\x18\x06 \x01(\x05R\x0fmaxOutputTokens\" \n" +
	"\n" +
	"ReduceSpec\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"Y\n" +
	"\aJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"\xcf\x01\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12*\n" +
	"\x05tasks\x18\x03 \x03(\v2\x14.edgemesh.TaskStatusR\x05tasks\x12!\n" +
	"\ffinal_result\x18\x04 \x01(\tR\vfinalResult\x12#\n" +
	"\rcurrent_group\x18\x05 \x01(\x05R\fcurrentGroup\x12!\n" +
	"\ftotal_groups\x18\x06 \x01(\x05R\vtotalGroups\"\xc9\x01\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12,\n" +
	"\x12assigned_device_id\x18\x02 \x01(\tR\x10assignedDeviceId\x120\n" +
	"\x14assigned_device_name\x18\x03 \x01(\tR\x12assignedDeviceName\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"g\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\"|\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x17\n" +
	"\atime_ms\x18\x05 \x01(\x01R\x06timeMs\"\x94\x01\n" +
	"\fWebRTCConfig\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"target_fps\x18\x02 \x01(\x05R\ttargetFps\x12!\n" +
	"\fjpeg_quality\x18\x03 \x01(\x05R\vjpegQuality\x12#\n" +
	"\rmonitor_index\x18\x04 \x01(\x05R\fmonitorIndex\"<\n" +
	"\vWebRTCOffer\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03sdp\x18\x02 \x01(\tR\x03sdp\"=\n" +
	"\fWebRTCAnswer\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03sdp\x18\x02 \x01(\tR\x03sdp\")\n" +
	"\n" +
	"WebRTCStop\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"h\n" +
	"\x12PlanPreviewRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1f\n" +
	"\vmax_workers\x18\x03 \x01(\x05R\n" +
	"maxWorkers\"\xb4\x01\n" +
	"\x13PlanPreviewResponse\x12\x17\n" +
	"\aused_ai\x18\x01 \x01(\bR\x06usedAi\x12\x14\n" +
	"\x05notes\x18\x02 \x01(\tR\x05notes\x12\x1c\n" +
	"\trationale\x18\x03 \x01(\tR\trationale\x12\"\n" +
	"\x04plan\x18\x04 \x01(\v2\x0e.edgemesh.PlanR\x04plan\x12,\n" +
	"\x06reduce\x18\x05 \x01(\v2\x14.edgemesh.ReduceSpecR\x06reduce\"s\n" +
	"\x0fPlanCostRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\x04plan\x18\x02 \x01(\v2\x0e.edgemesh.PlanR\x04plan\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x03 \x03(\tR\tdeviceIds\"\xb3\x02\n" +
	"\x10PlanCostResponse\x12,\n" +
	"\x12total_predicted_ms\x18\x01 \x01(\x01R\x10totalPredictedMs\x12?\n" +
	"\fdevice_costs\x18\x02 \x03(\v2\x1c.edgemesh.DeviceCostEstimateR\vdeviceCosts\x122\n" +
	"\x15recommended_device_id\x18\x03 \x01(\tR\x13recommendedDeviceId\x126\n" +
	"\x17recommended_device_name\x18\x04 \x01(\tR\x15recommendedDeviceName\x12*\n" +
	"\x11has_unknown_costs\x18\x05 \x01(\bR\x0fhasUnknownCosts\x12\x18\n" +
	"\awarning\x18\x06 \x01(\tR\awarning\"\x82\x02\n" +
	"\x12DeviceCostEstimate\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x19\n" +
	"\btotal_ms\x18\x03 \x01(\x01R\atotalMs\x129\n" +
	"\n" +
	"step_costs\x18\x04 \x03(\v2\x1a.edgemesh.StepCostEstimateR\tstepCosts\x121\n" +
	"\x15estimated_peak_ram_mb\x18\x05 \x01(\x04R\x12estimatedPeakRamMb\x12%\n" +
	"\x0eram_sufficient\x18\x06 \x01(\bR\rramSufficient\"\xcb\x01\n" +
	"\x10StepCostEstimate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12!\n" +
	"\fpredicted_ms\x18\x03 \x01(\x01R\vpredictedMs\x12.\n" +
	"\x13predicted_memory_mb\x18\x04 \x01(\x01R\x11predictedMemoryMb\x12!\n" +
	"\funknown_cost\x18\x05 \x01(\bR\vunknownCost\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\"+\n" +
	"\x15DownloadTicketRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x91\x01\n" +
	"\x16DownloadTicketResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12&\n" +
	"\x0fexpires_unix_ms\x18\x04 \x01(\x03R\rexpiresUnixMs2\xa6\t\n" +
	"\x13OrchestratorService\x12=\n" +
	"\rCreateSession\x12\x15.edgemesh.AuthRequest\x1a\x15.edgemesh.SessionInfo\x123\n" +
	"\tHeartbeat\x12\x15.edgemesh.SessionInfo\x1a\x0f.edgemesh.Empty\x12E\n" +
	"\x0eExecuteCommand\x12\x18.edgemesh.CommandRequest\x1a\x19.edgemesh.CommandResponse\x12;\n" +
	"\x0eRegisterDevice\x12\x14.edgemesh.DeviceInfo\x1a\x13.edgemesh.DeviceAck\x12J\n" +
	"\vListDevices\x12\x1c.edgemesh.ListDevicesRequest\x1a\x1d.edgemesh.ListDevicesResponse\x12=\n" +
	"\x0fGetDeviceStatus\x12\x12.edgemesh.DeviceId\x1a\x16.edgemesh.DeviceStatus\x12>\n" +
	"\tRunAITask\x12\x17.edgemesh.AITaskRequest\x1a\x18.edgemesh.AITaskResponse\x126\n" +
	"\vHealthCheck\x12\x0f.edgemesh.Empty\x1a\x16.edgemesh.HealthStatus\x12W\n" +
	"\x14ExecuteRoutedCommand\x12\x1e.edgemesh.RoutedCommandRequest\x1a\x1f.edgemesh.RoutedCommandResponse\x124\n" +
	"\tSubmitJob\x12\x14.edgemesh.JobRequest\x1a\x11.edgemesh.JobInfo\x12.\n" +
	"\x06GetJob\x12\x0f.edgemesh.JobId\x1a\x13.edgemesh.JobStatus\x126\n" +
	"\aRunTask\x12\x15.edgemesh.TaskRequest\x1a\x14.edgemesh.TaskResult\x12J\n" +
	"\vPreviewPlan\x12\x1c.edgemesh.PlanPreviewRequest\x1a\x1d.edgemesh.PlanPreviewResponse\x12H\n" +
	"\x0fPreviewPlanCost\x12\x19.edgemesh.PlanCostRequest\x1a\x1a.edgemesh.PlanCostResponse\x12<\n" +
	"\vStartWebRTC\x12\x16.edgemesh.WebRTCConfig\x1a\x15.edgemesh.WebRTCOffer\x129\n" +
	"\x0eCompleteWebRTC\x12\x16.edgemesh.WebRTCAnswer\x1a\x0f.edgemesh.Empty\x123\n" +
	"\n" +
	"StopWebRTC\x12\x14.edgemesh.WebRTCStop\x1a\x0f.edgemesh.Empty\x12Y\n" +
	"\x14CreateDownloadTicket\x12\x1f.edgemesh.DownloadTicketRequest\x1a .edgemesh.DownloadTicketResponseB\"Z github.com/edgecli/edgecli/protob\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_orchestrator_proto_goTypes = []any{
	(RoutingPolicy_Mode)(0),        // 0: edgemesh.RoutingPolicy.Mode
	(*Empty)(nil),                  // 1: edgemesh.Empty
	(*AuthRequest)(nil),            // 2: edgemesh.AuthRequest
	(*SessionInfo)(nil),            // 3: edgemesh.SessionInfo
	(*CommandRequest)(nil),         // 4: edgemesh.CommandRequest
	(*CommandResponse)(nil),        // 5: edgemesh.CommandResponse
	(*DeviceId)(nil),               // 6: edgemesh.DeviceId
	(*DeviceInfo)(nil),             // 7: edgemesh.DeviceInfo
	(*DeviceAck)(nil),              // 8: edgemesh.DeviceAck
	(*DeviceStatus)(nil),           // 9: edgemesh.DeviceStatus
	(*ListDevicesRequest)(nil),     // 10: edgemesh.ListDevicesRequest
	(*ListDevicesResponse)(nil),    // 11: edgemesh.ListDevicesResponse
	(*AITaskRequest)(nil),          // 12: edgemesh.AITaskRequest
	(*AITaskResponse)(nil),         // 13: edgemesh.AITaskResponse
	(*HealthStatus)(nil),           // 14: edgemesh.HealthStatus
	(*RoutingPolicy)(nil),          // 15: edgemesh.RoutingPolicy
	(*RoutedCommandRequest)(nil),   // 16: edgemesh.RoutedCommandRequest
	(*RoutedCommandResponse)(nil),  // 17: edgemesh.RoutedCommandResponse
	(*JobId)(nil),                  // 18: edgemesh.JobId
	(*JobRequest)(nil),             // 19: edgemesh.JobRequest
	(*Plan)(nil),                   // 20: edgemesh.Plan
	(*TaskGroup)(nil),              // 21: edgemesh.TaskGroup
	(*TaskSpec)(nil),               // 22: edgemesh.TaskSpec
	(*ReduceSpec)(nil),             // 23: edgemesh.ReduceSpec
	(*JobInfo)(nil),                // 24: edgemesh.JobInfo
	(*JobStatus)(nil),              // 25: edgemesh.JobStatus
	(*TaskStatus)(nil),             // 26: edgemesh.TaskStatus
	(*TaskRequest)(nil),            // 27: edgemesh.TaskRequest
	(*TaskResult)(nil),             // 28: edgemesh.TaskResult
	(*WebRTCConfig)(nil),           // 29: edgemesh.WebRTCConfig
	(*WebRTCOffer)(nil),            // 30: edgemesh.WebRTCOffer
	(*WebRTCAnswer)(nil),           // 31: edgemesh.WebRTCAnswer
	(*WebRTCStop)(nil),             // 32: edgemesh.WebRTCStop
	(*PlanPreviewRequest)(nil),     // 33: edgemesh.PlanPreviewRequest
	(*PlanPreviewResponse)(nil),    // 34: edgemesh.PlanPreviewResponse
	(*PlanCostRequest)(nil),        // 35: edgemesh.PlanCostRequest
	(*PlanCostResponse)(nil),       // 36: edgemesh.PlanCostResponse
	(*DeviceCostEstimate)(nil),     // 37: edgemesh.DeviceCostEstimate
	(*StepCostEstimate)(nil),       // 38: edgemesh.StepCostEstimate
	(*DownloadTicketRequest)(nil),  // 39: edgemesh.DownloadTicketRequest
	(*DownloadTicketResponse)(nil), // 40: edgemesh.DownloadTicketResponse
}
var file_orchestrator_proto_depIdxs = []int32{
	7,  // 0: edgemesh.ListDevicesResponse.devices:type_name -> edgemesh.DeviceInfo
	0,  // 1: edgemesh.RoutingPolicy.mode:type_name -> edgemesh.RoutingPolicy.Mode
	15, // 2: edgemesh.RoutedCommandRequest.policy:type_name -> edgemesh.RoutingPolicy
	5,  // 3: edgemesh.RoutedCommandResponse.output:type_name -> edgemesh.CommandResponse
	20, // 4: edgemesh.JobRequest.plan:type_name -> edgemesh.Plan
	23, // 5: edgemesh.JobRequest.reduce:type_name -> edgemesh.ReduceSpec
	21, // 6: edgemesh.Plan.groups:type_name -> edgemesh.TaskGroup
	22, // 7: edgemesh.TaskGroup.tasks:type_name -> edgemesh.TaskSpec
	26, // 8: edgemesh.JobStatus.tasks:type_name -> edgemesh.TaskStatus
	20, // 9: edgemesh.PlanPreviewResponse.plan:type_name -> edgemesh.Plan
	23, // 10: edgemesh.PlanPreviewResponse.reduce:type_name -> edgemesh.ReduceSpec
	20, // 11: edgemesh.PlanCostRequest.plan:type_name -> edgemesh.Plan
	37, // 12: edgemesh.PlanCostResponse.device_costs:type_name -> edgemesh.DeviceCostEstimate
	38, // 13: edgemesh.DeviceCostEstimate.step_costs:type_name -> edgemesh.StepCostEstimate
	2,  // 14: edgemesh.OrchestratorService.CreateSession:input_type -> edgemesh.AuthRequest
	3,  // 15: edgemesh.OrchestratorService.Heartbeat:input_type -> edgemesh.SessionInfo
	4,  // 16: edgemesh.OrchestratorService.ExecuteCommand:input_type -> edgemesh.CommandRequest
	7,  // 17: edgemesh.OrchestratorService.RegisterDevice:input_type -> edgemesh.DeviceInfo
	10, // 18: edgemesh.OrchestratorService.ListDevices:input_type -> edgemesh.ListDevicesRequest
	6,  // 19: edgemesh.OrchestratorService.GetDeviceStatus:input_type -> edgemesh.DeviceId
	12, // 20: edgemesh.OrchestratorService.RunAITask:input_type -> edgemesh.AITaskRequest
	1,  // 21: edgemesh.OrchestratorService.HealthCheck:input_type -> edgemesh.Empty
	16, // 22: edgemesh.OrchestratorService.ExecuteRoutedCommand:input_type -> edgemesh.RoutedCommandRequest
	19, // 23: edgemesh.OrchestratorService.SubmitJob:input_type -> edgemesh.JobRequest
	18, // 24: edgemesh.OrchestratorService.GetJob:input_type -> edgemesh.JobId
	27, // 25: edgemesh.OrchestratorService.RunTask:input_type -> edgemesh.TaskRequest
	33, // 26: edgemesh.OrchestratorService.PreviewPlan:input_type -> edgemesh.PlanPreviewRequest
	35, // 27: edgemesh.OrchestratorService.PreviewPlanCost:input_type -> edgemesh.PlanCostRequest
	29, // 28: edgemesh.OrchestratorService.StartWebRTC:input_type -> edgemesh.WebRTCConfig
	31, // 29: edgemesh.OrchestratorService.CompleteWebRTC:input_type -> edgemesh.WebRTCAnswer
	32, // 30: edgemesh.OrchestratorService.StopWebRTC:input_type -> edgemesh.WebRTCStop
	39, // 31: edgemesh.OrchestratorService.CreateDownloadTicket:input_type -> edgemesh.DownloadTicketRequest
	3,  // 32: edgemesh.OrchestratorService.CreateSession:output_type -> edgemesh.SessionInfo
	1,  // 33: edgemesh.OrchestratorService.Heartbeat:output_type -> edgemesh.Empty
	5,  // 34: edgemesh.OrchestratorService.ExecuteCommand:output_type -> edgemesh.CommandResponse
	8,  // 35: edgemesh.OrchestratorService.RegisterDevice:output_type -> edgemesh.DeviceAck
	11, // 36: edgemesh.OrchestratorService.ListDevices:output_type -> edgemesh.ListDevicesResponse
	9,  // 37: edgemesh.OrchestratorService.GetDeviceStatus:output_type -> edgemesh.DeviceStatus
	13, // 38: edgemesh.OrchestratorService.RunAITask:output_type -> edgemesh.AITaskResponse
	14, // 39: edgemesh.OrchestratorService.HealthCheck:output_type -> edgemesh.HealthStatus
	17, // 40: edgemesh.OrchestratorService.ExecuteRoutedCommand:output_type -> edgemesh.RoutedCommandResponse
	24, // 41: edgemesh.OrchestratorService.SubmitJob:output_type -> edgemesh.JobInfo
	25, // 42: edgemesh.OrchestratorService.GetJob:output_type -> edgemesh.JobStatus
	28, // 43: edgemesh.OrchestratorService.RunTask:output_type -> edgemesh.TaskResult
	34, // 44: edgemesh.OrchestratorService.PreviewPlan:output_type -> edgemesh.PlanPreviewResponse
	36, // 45: edgemesh.OrchestratorService.PreviewPlanCost:output_type -> edgemesh.PlanCostResponse
	30, // 46: edgemesh.OrchestratorService.StartWebRTC:output_type -> edgemesh.WebRTCOffer
	1,  // 47: edgemesh.OrchestratorService.CompleteWebRTC:output_type -> edgemesh.Empty
	1,  // 48: edgemesh.OrchestratorService.StopWebRTC:output_type -> edgemesh.Empty
	40, // 49: edgemesh.OrchestratorService.CreateDownloadTicket:output_type -> edgemesh.DownloadTicketResponse
	32, // [32:50] is the sub-list for method output_type
	14, // [14:32] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		EnumInfos:         file_orchestrator_proto_enumTypes,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
