// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	SecurityKey   string                 `protobuf:"bytes,2,opt,name=security_key,json=securityKey,proto3" json:"security_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AuthRequest) GetSecurityKey() string {
	if x != nil {
		return x.SecurityKey
	}
	return ""
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	HostName      string                 `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	ConnectedAt   int64                  `protobuf:"varint,3,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *SessionInfo) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *CommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type DeviceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceId) Reset() {
	*x = DeviceId{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceId) ProtoMessage() {}

func (x *DeviceId) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceId.ProtoReflect.Descriptor instead.
func (*DeviceId) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceId) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // stable id generated by device at first run (uuid stored on disk)
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"` // "chinmay-mac", "windows-laptop", etc
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`                       // "macos", "windows", "linux", "android"
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`                               // "amd64", "arm64"
	HasCpu        bool                   `protobuf:"varint,5,opt,name=has_cpu,json=hasCpu,proto3" json:"has_cpu,omitempty"`            // always true
	HasGpu        bool                   `protobuf:"varint,6,opt,name=has_gpu,json=hasGpu,proto3" json:"has_gpu,omitempty"`
	HasNpu        bool                   `protobuf:"varint,7,opt,name=has_npu,json=hasNpu,proto3" json:"has_npu,omitempty"`      // false for now, will be true on Snapdragon later
	GrpcAddr      string                 `protobuf:"bytes,8,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"` // where this device can be reached, e.g. "10.0.0.5:50051"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *DeviceInfo) GetHasCpu() bool {
	if x != nil {
		return x.HasCpu
	}
	return false
}

func (x *DeviceInfo) GetHasGpu() bool {
	if x != nil {
		return x.HasGpu
	}
	return false
}

func (x *DeviceInfo) GetHasNpu() bool {
	if x != nil {
		return x.HasNpu
	}
	return false
}

func (x *DeviceInfo) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

type DeviceAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RegisteredAt  int64                  `protobuf:"varint,2,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceAck) Reset() {
	*x = DeviceAck{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAck) ProtoMessage() {}

func (x *DeviceAck) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAck.ProtoReflect.Descriptor instead.
func (*DeviceAck) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeviceAck) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

type DeviceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastSeen      int64                  `protobuf:"varint,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // unix seconds
	CpuLoad       float64                `protobuf:"fixed64,3,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`   // 0..1, or -1 if unavailable
	MemUsedMb     uint64                 `protobuf:"varint,4,opt,name=mem_used_mb,json=memUsedMb,proto3" json:"mem_used_mb,omitempty"`
	MemTotalMb    uint64                 `protobuf:"varint,5,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatus) Reset() {
	*x = DeviceStatus{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatus) ProtoMessage() {}

func (x *DeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatus.ProtoReflect.Descriptor instead.
func (*DeviceStatus) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceStatus) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *DeviceStatus) GetCpuLoad() float64 {
	if x != nil {
		return x.CpuLoad
	}
	return 0
}

func (x *DeviceStatus) GetMemUsedMb() uint64 {
	if x != nil {
		return x.MemUsedMb
	}
	return 0
}

func (x *DeviceStatus) GetMemTotalMb() uint64 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type AITaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`   // "summarize", "transcribe", "analyze_screen"
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"` // for now, just raw text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AITaskRequest) Reset() {
	*x = AITaskRequest{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AITaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AITaskRequest) ProtoMessage() {}

func (x *AITaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AITaskRequest.ProtoReflect.Descriptor instead.
func (*AITaskRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *AITaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AITaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *AITaskRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type AITaskResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SelectedDeviceId   string                 `protobuf:"bytes,1,opt,name=selected_device_id,json=selectedDeviceId,proto3" json:"selected_device_id,omitempty"`
	SelectedDeviceAddr string                 `protobuf:"bytes,2,opt,name=selected_device_addr,json=selectedDeviceAddr,proto3" json:"selected_device_addr,omitempty"`
	WouldUseNpu        bool                   `protobuf:"varint,3,opt,name=would_use_npu,json=wouldUseNpu,proto3" json:"would_use_npu,omitempty"`
	Result             string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"` // stub result: "ROUTED: <task> to <device_name>"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AITaskResponse) Reset() {
	*x = AITaskResponse{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AITaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AITaskResponse) ProtoMessage() {}

func (x *AITaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AITaskResponse.ProtoReflect.Descriptor instead.
func (*AITaskResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *AITaskResponse) GetSelectedDeviceId() string {
	if x != nil {
		return x.SelectedDeviceId
	}
	return ""
}

func (x *AITaskResponse) GetSelectedDeviceAddr() string {
	if x != nil {
		return x.SelectedDeviceAddr
	}
	return ""
}

func (x *AITaskResponse) GetWouldUseNpu() bool {
	if x != nil {
		return x.WouldUseNpu
	}
	return false
}

func (x *AITaskResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\bedgemesh\"\a\n" +
	"\x05Empty\"Q\n" +
	"\vAuthRequest\x12\x1f\n" +
	"\vdevice_name\x18\x01 \x01(\tR\n" +
	"deviceName\x12!\n" +
	"\fsecurity_key\x18\x02 \x01(\tR\vsecurityKey\"l\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12!\n" +
	"\fconnected_at\x18\x03 \x01(\x03R\vconnectedAt\"]\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\"^\n" +
	"\x0fCommandResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\"'\n" +
	"\bDeviceId\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\xe2\x01\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x17\n" +
	"\ahas_cpu\x18\x05 \x01(\bR\x06hasCpu\x12\x17\n" +
	"\ahas_gpu\x18\x06 \x01(\bR\x06hasGpu\x12\x17\n" +
	"\ahas_npu\x18\a \x01(\bR\x06hasNpu\x12\x1b\n" +
	"\tgrpc_addr\x18\b \x01(\tR\bgrpcAddr\"@\n" +
	"\tDeviceAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\rregistered_at\x18\x02 \x01(\x03R\fregisteredAt\"\xa5\x01\n" +
	"\fDeviceStatus\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tlast_seen\x18\x02 \x01(\x03R\blastSeen\x12\x19\n" +
	"\bcpu_load\x18\x03 \x01(\x01R\acpuLoad\x12\x1e\n" +
	"\vmem_used_mb\x18\x04 \x01(\x04R\tmemUsedMb\x12 \n" +
	"\fmem_total_mb\x18\x05 \x01(\x04R\n" +
	"memTotalMb\"\x14\n" +
	"\x12ListDevicesRequest\"E\n" +
	"\x13ListDevicesResponse\x12.\n" +
	"\adevices\x18\x01 \x03(\v2\x14.edgemesh.DeviceInfoR\adevices\"X\n" +
	"\rAITaskRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"\xac\x01\n" +
	"\x0eAITaskResponse\x12,\n" +
	"\x12selected_device_id\x18\x01 \x01(\tR\x10selectedDeviceId\x120\n" +
	"\x14selected_device_addr\x18\x02 \x01(\tR\x12selectedDeviceAddr\x12\"\n" +
	"\rwould_use_npu\x18\x03 \x01(\bR\vwouldUseNpu\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result2\xd8\x03\n" +
	"\x13OrchestratorService\x12=\n" +
	"\rCreateSession\x12\x15.edgemesh.AuthRequest\x1a\x15.edgemesh.SessionInfo\x123\n" +
	"\tHeartbeat\x12\x15.edgemesh.SessionInfo\x1a\x0f.edgemesh.Empty\x12E\n" +
	"\x0eExecuteCommand\x12\x18.edgemesh.CommandRequest\x1a\x19.edgemesh.CommandResponse\x12;\n" +
	"\x0eRegisterDevice\x12\x14.edgemesh.DeviceInfo\x1a\x13.edgemesh.DeviceAck\x12J\n" +
	"\vListDevices\x12\x1c.edgemesh.ListDevicesRequest\x1a\x1d.edgemesh.ListDevicesResponse\x12=\n" +
	"\x0fGetDeviceStatus\x12\x12.edgemesh.DeviceId\x1a\x16.edgemesh.DeviceStatus\x12>\n" +
	"\tRunAITask\x12\x17.edgemesh.AITaskRequest\x1a\x18.edgemesh.AITaskResponseB\"Z github.com/edgecli/edgecli/protob\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_orchestrator_proto_goTypes = []any{
	(*Empty)(nil),               // 0: edgemesh.Empty
	(*AuthRequest)(nil),         // 1: edgemesh.AuthRequest
	(*SessionInfo)(nil),         // 2: edgemesh.SessionInfo
	(*CommandRequest)(nil),      // 3: edgemesh.CommandRequest
	(*CommandResponse)(nil),     // 4: edgemesh.CommandResponse
	(*DeviceId)(nil),            // 5: edgemesh.DeviceId
	(*DeviceInfo)(nil),          // 6: edgemesh.DeviceInfo
	(*DeviceAck)(nil),           // 7: edgemesh.DeviceAck
	(*DeviceStatus)(nil),        // 8: edgemesh.DeviceStatus
	(*ListDevicesRequest)(nil),  // 9: edgemesh.ListDevicesRequest
	(*ListDevicesResponse)(nil), // 10: edgemesh.ListDevicesResponse
	(*AITaskRequest)(nil),       // 11: edgemesh.AITaskRequest
	(*AITaskResponse)(nil),      // 12: edgemesh.AITaskResponse
}
var file_orchestrator_proto_depIdxs = []int32{
	6,  // 0: edgemesh.ListDevicesResponse.devices:type_name -> edgemesh.DeviceInfo
	1,  // 1: edgemesh.OrchestratorService.CreateSession:input_type -> edgemesh.AuthRequest
	2,  // 2: edgemesh.OrchestratorService.Heartbeat:input_type -> edgemesh.SessionInfo
	3,  // 3: edgemesh.OrchestratorService.ExecuteCommand:input_type -> edgemesh.CommandRequest
	6,  // 4: edgemesh.OrchestratorService.RegisterDevice:input_type -> edgemesh.DeviceInfo
	9,  // 5: edgemesh.OrchestratorService.ListDevices:input_type -> edgemesh.ListDevicesRequest
	5,  // 6: edgemesh.OrchestratorService.GetDeviceStatus:input_type -> edgemesh.DeviceId
	11, // 7: edgemesh.OrchestratorService.RunAITask:input_type -> edgemesh.AITaskRequest
	2,  // 8: edgemesh.OrchestratorService.CreateSession:output_type -> edgemesh.SessionInfo
	0,  // 9: edgemesh.OrchestratorService.Heartbeat:output_type -> edgemesh.Empty
	4,  // 10: edgemesh.OrchestratorService.ExecuteCommand:output_type -> edgemesh.CommandResponse
	7,  // 11: edgemesh.OrchestratorService.RegisterDevice:output_type -> edgemesh.DeviceAck
	10, // 12: edgemesh.OrchestratorService.ListDevices:output_type -> edgemesh.ListDevicesResponse
	8,  // 13: edgemesh.OrchestratorService.GetDeviceStatus:output_type -> edgemesh.DeviceStatus
	12, // 14: edgemesh.OrchestratorService.RunAITask:output_type -> edgemesh.AITaskResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
