// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: orchestrator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorService_CreateSession_FullMethodName        = "/edgemesh.OrchestratorService/CreateSession"
	OrchestratorService_Heartbeat_FullMethodName            = "/edgemesh.OrchestratorService/Heartbeat"
	OrchestratorService_ExecuteCommand_FullMethodName       = "/edgemesh.OrchestratorService/ExecuteCommand"
	OrchestratorService_RegisterDevice_FullMethodName       = "/edgemesh.OrchestratorService/RegisterDevice"
	OrchestratorService_ListDevices_FullMethodName          = "/edgemesh.OrchestratorService/ListDevices"
	OrchestratorService_GetDeviceStatus_FullMethodName      = "/edgemesh.OrchestratorService/GetDeviceStatus"
	OrchestratorService_RunAITask_FullMethodName            = "/edgemesh.OrchestratorService/RunAITask"
	OrchestratorService_HealthCheck_FullMethodName          = "/edgemesh.OrchestratorService/HealthCheck"
	OrchestratorService_ExecuteRoutedCommand_FullMethodName = "/edgemesh.OrchestratorService/ExecuteRoutedCommand"
	OrchestratorService_SubmitJob_FullMethodName            = "/edgemesh.OrchestratorService/SubmitJob"
	OrchestratorService_GetJob_FullMethodName               = "/edgemesh.OrchestratorService/GetJob"
	OrchestratorService_RunTask_FullMethodName              = "/edgemesh.OrchestratorService/RunTask"
	OrchestratorService_PreviewPlan_FullMethodName          = "/edgemesh.OrchestratorService/PreviewPlan"
	OrchestratorService_PreviewPlanCost_FullMethodName      = "/edgemesh.OrchestratorService/PreviewPlanCost"
	OrchestratorService_StartWebRTC_FullMethodName          = "/edgemesh.OrchestratorService/StartWebRTC"
	OrchestratorService_CompleteWebRTC_FullMethodName       = "/edgemesh.OrchestratorService/CompleteWebRTC"
	OrchestratorService_StopWebRTC_FullMethodName           = "/edgemesh.OrchestratorService/StopWebRTC"
	OrchestratorService_CreateDownloadTicket_FullMethodName = "/edgemesh.OrchestratorService/CreateDownloadTicket"
	OrchestratorService_ReadFile_FullMethodName             = "/edgemesh.OrchestratorService/ReadFile"
	OrchestratorService_SyncChatMemory_FullMethodName       = "/edgemesh.OrchestratorService/SyncChatMemory"
	OrchestratorService_GetChatMemory_FullMethodName        = "/edgemesh.OrchestratorService/GetChatMemory"
	OrchestratorService_RunLLMTask_FullMethodName           = "/edgemesh.OrchestratorService/RunLLMTask"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorServiceClient interface {
	// Session management
	CreateSession(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*SessionInfo, error)
	Heartbeat(ctx context.Context, in *SessionInfo, opts ...grpc.CallOption) (*Empty, error)
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// Device discovery and orchestration
	RegisterDevice(ctx context.Context, in *DeviceInfo, opts ...grpc.CallOption) (*DeviceAck, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	GetDeviceStatus(ctx context.Context, in *DeviceId, opts ...grpc.CallOption) (*DeviceStatus, error)
	// AI task routing
	RunAITask(ctx context.Context, in *AITaskRequest, opts ...grpc.CallOption) (*AITaskResponse, error)
	// Connectivity check
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
	// Routed execution - forwards command to best available device
	ExecuteRoutedCommand(ctx context.Context, in *RoutedCommandRequest, opts ...grpc.CallOption) (*RoutedCommandResponse, error)
	// Job orchestration (push model)
	SubmitJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobInfo, error)
	GetJob(ctx context.Context, in *JobId, opts ...grpc.CallOption) (*JobStatus, error)
	// Worker execution
	RunTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResult, error)
	// Plan preview (no execution)
	PreviewPlan(ctx context.Context, in *PlanPreviewRequest, opts ...grpc.CallOption) (*PlanPreviewResponse, error)
	// Plan cost estimation
	PreviewPlanCost(ctx context.Context, in *PlanCostRequest, opts ...grpc.CallOption) (*PlanCostResponse, error)
	// WebRTC screen streaming
	StartWebRTC(ctx context.Context, in *WebRTCConfig, opts ...grpc.CallOption) (*WebRTCOffer, error)
	CompleteWebRTC(ctx context.Context, in *WebRTCAnswer, opts ...grpc.CallOption) (*Empty, error)
	StopWebRTC(ctx context.Context, in *WebRTCStop, opts ...grpc.CallOption) (*Empty, error)
	// File download ticket
	CreateDownloadTicket(ctx context.Context, in *DownloadTicketRequest, opts ...grpc.CallOption) (*DownloadTicketResponse, error)
	// File reading (for LLM tool calling)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	// Chat memory synchronization
	SyncChatMemory(ctx context.Context, in *ChatMemorySync, opts ...grpc.CallOption) (*ChatMemorySyncResponse, error)
	GetChatMemory(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChatMemoryData, error)
	// Remote LLM task execution
	RunLLMTask(ctx context.Context, in *LLMTaskRequest, opts ...grpc.CallOption) (*LLMTaskResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) CreateSession(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*SessionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, OrchestratorService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) Heartbeat(ctx context.Context, in *SessionInfo, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OrchestratorService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) RegisterDevice(ctx context.Context, in *DeviceInfo, opts ...grpc.CallOption) (*DeviceAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceAck)
	err := c.cc.Invoke(ctx, OrchestratorService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetDeviceStatus(ctx context.Context, in *DeviceId, opts ...grpc.CallOption) (*DeviceStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceStatus)
	err := c.cc.Invoke(ctx, OrchestratorService_GetDeviceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) RunAITask(ctx context.Context, in *AITaskRequest, opts ...grpc.CallOption) (*AITaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AITaskResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_RunAITask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, OrchestratorService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ExecuteRoutedCommand(ctx context.Context, in *RoutedCommandRequest, opts ...grpc.CallOption) (*RoutedCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutedCommandResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ExecuteRoutedCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) SubmitJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobInfo)
	err := c.cc.Invoke(ctx, OrchestratorService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetJob(ctx context.Context, in *JobId, opts ...grpc.CallOption) (*JobStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, OrchestratorService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) RunTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResult)
	err := c.cc.Invoke(ctx, OrchestratorService_RunTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) PreviewPlan(ctx context.Context, in *PlanPreviewRequest, opts ...grpc.CallOption) (*PlanPreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanPreviewResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_PreviewPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) PreviewPlanCost(ctx context.Context, in *PlanCostRequest, opts ...grpc.CallOption) (*PlanCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanCostResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_PreviewPlanCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) StartWebRTC(ctx context.Context, in *WebRTCConfig, opts ...grpc.CallOption) (*WebRTCOffer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebRTCOffer)
	err := c.cc.Invoke(ctx, OrchestratorService_StartWebRTC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) CompleteWebRTC(ctx context.Context, in *WebRTCAnswer, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OrchestratorService_CompleteWebRTC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) StopWebRTC(ctx context.Context, in *WebRTCStop, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OrchestratorService_StopWebRTC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) CreateDownloadTicket(ctx context.Context, in *DownloadTicketRequest, opts ...grpc.CallOption) (*DownloadTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadTicketResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_CreateDownloadTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) SyncChatMemory(ctx context.Context, in *ChatMemorySync, opts ...grpc.CallOption) (*ChatMemorySyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMemorySyncResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_SyncChatMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetChatMemory(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChatMemoryData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMemoryData)
	err := c.cc.Invoke(ctx, OrchestratorService_GetChatMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) RunLLMTask(ctx context.Context, in *LLMTaskRequest, opts ...grpc.CallOption) (*LLMTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLMTaskResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_RunLLMTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
type OrchestratorServiceServer interface {
	// Session management
	CreateSession(context.Context, *AuthRequest) (*SessionInfo, error)
	Heartbeat(context.Context, *SessionInfo) (*Empty, error)
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	// Device discovery and orchestration
	RegisterDevice(context.Context, *DeviceInfo) (*DeviceAck, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	GetDeviceStatus(context.Context, *DeviceId) (*DeviceStatus, error)
	// AI task routing
	RunAITask(context.Context, *AITaskRequest) (*AITaskResponse, error)
	// Connectivity check
	HealthCheck(context.Context, *Empty) (*HealthStatus, error)
	// Routed execution - forwards command to best available device
	ExecuteRoutedCommand(context.Context, *RoutedCommandRequest) (*RoutedCommandResponse, error)
	// Job orchestration (push model)
	SubmitJob(context.Context, *JobRequest) (*JobInfo, error)
	GetJob(context.Context, *JobId) (*JobStatus, error)
	// Worker execution
	RunTask(context.Context, *TaskRequest) (*TaskResult, error)
	// Plan preview (no execution)
	PreviewPlan(context.Context, *PlanPreviewRequest) (*PlanPreviewResponse, error)
	// Plan cost estimation
	PreviewPlanCost(context.Context, *PlanCostRequest) (*PlanCostResponse, error)
	// WebRTC screen streaming
	StartWebRTC(context.Context, *WebRTCConfig) (*WebRTCOffer, error)
	CompleteWebRTC(context.Context, *WebRTCAnswer) (*Empty, error)
	StopWebRTC(context.Context, *WebRTCStop) (*Empty, error)
	// File download ticket
	CreateDownloadTicket(context.Context, *DownloadTicketRequest) (*DownloadTicketResponse, error)
	// File reading (for LLM tool calling)
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	// Chat memory synchronization
	SyncChatMemory(context.Context, *ChatMemorySync) (*ChatMemorySyncResponse, error)
	GetChatMemory(context.Context, *Empty) (*ChatMemoryData, error)
	// Remote LLM task execution
	RunLLMTask(context.Context, *LLMTaskRequest) (*LLMTaskResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) CreateSession(context.Context, *AuthRequest) (*SessionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedOrchestratorServiceServer) Heartbeat(context.Context, *SessionInfo) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedOrchestratorServiceServer) ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedOrchestratorServiceServer) RegisterDevice(context.Context, *DeviceInfo) (*DeviceAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedOrchestratorServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetDeviceStatus(context.Context, *DeviceId) (*DeviceStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceStatus not implemented")
}
func (UnimplementedOrchestratorServiceServer) RunAITask(context.Context, *AITaskRequest) (*AITaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunAITask not implemented")
}
func (UnimplementedOrchestratorServiceServer) HealthCheck(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedOrchestratorServiceServer) ExecuteRoutedCommand(context.Context, *RoutedCommandRequest) (*RoutedCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteRoutedCommand not implemented")
}
func (UnimplementedOrchestratorServiceServer) SubmitJob(context.Context, *JobRequest) (*JobInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetJob(context.Context, *JobId) (*JobStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedOrchestratorServiceServer) RunTask(context.Context, *TaskRequest) (*TaskResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedOrchestratorServiceServer) PreviewPlan(context.Context, *PlanPreviewRequest) (*PlanPreviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewPlan not implemented")
}
func (UnimplementedOrchestratorServiceServer) PreviewPlanCost(context.Context, *PlanCostRequest) (*PlanCostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewPlanCost not implemented")
}
func (UnimplementedOrchestratorServiceServer) StartWebRTC(context.Context, *WebRTCConfig) (*WebRTCOffer, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWebRTC not implemented")
}
func (UnimplementedOrchestratorServiceServer) CompleteWebRTC(context.Context, *WebRTCAnswer) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteWebRTC not implemented")
}
func (UnimplementedOrchestratorServiceServer) StopWebRTC(context.Context, *WebRTCStop) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopWebRTC not implemented")
}
func (UnimplementedOrchestratorServiceServer) CreateDownloadTicket(context.Context, *DownloadTicketRequest) (*DownloadTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDownloadTicket not implemented")
}
func (UnimplementedOrchestratorServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedOrchestratorServiceServer) SyncChatMemory(context.Context, *ChatMemorySync) (*ChatMemorySyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncChatMemory not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetChatMemory(context.Context, *Empty) (*ChatMemoryData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatMemory not implemented")
}
func (UnimplementedOrchestratorServiceServer) RunLLMTask(context.Context, *LLMTaskRequest) (*LLMTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunLLMTask not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).CreateSession(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).Heartbeat(ctx, req.(*SessionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ExecuteCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RegisterDevice(ctx, req.(*DeviceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetDeviceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetDeviceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetDeviceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetDeviceStatus(ctx, req.(*DeviceId))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_RunAITask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AITaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RunAITask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RunAITask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RunAITask(ctx, req.(*AITaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ExecuteRoutedCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutedCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ExecuteRoutedCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ExecuteRoutedCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ExecuteRoutedCommand(ctx, req.(*RoutedCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).SubmitJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetJob(ctx, req.(*JobId))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RunTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RunTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_PreviewPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).PreviewPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_PreviewPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).PreviewPlan(ctx, req.(*PlanPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_PreviewPlanCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).PreviewPlanCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_PreviewPlanCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).PreviewPlanCost(ctx, req.(*PlanCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_StartWebRTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebRTCConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).StartWebRTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_StartWebRTC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).StartWebRTC(ctx, req.(*WebRTCConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_CompleteWebRTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebRTCAnswer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).CompleteWebRTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_CompleteWebRTC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).CompleteWebRTC(ctx, req.(*WebRTCAnswer))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_StopWebRTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebRTCStop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).StopWebRTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_StopWebRTC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).StopWebRTC(ctx, req.(*WebRTCStop))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_CreateDownloadTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).CreateDownloadTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_CreateDownloadTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).CreateDownloadTicket(ctx, req.(*DownloadTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_SyncChatMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMemorySync)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).SyncChatMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_SyncChatMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).SyncChatMemory(ctx, req.(*ChatMemorySync))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetChatMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetChatMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetChatMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetChatMemory(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_RunLLMTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLMTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RunLLMTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RunLLMTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RunLLMTask(ctx, req.(*LLMTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edgemesh.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _OrchestratorService_CreateSession_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _OrchestratorService_Heartbeat_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _OrchestratorService_ExecuteCommand_Handler,
		},
		{
			MethodName: "RegisterDevice",
			Handler:    _OrchestratorService_RegisterDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _OrchestratorService_ListDevices_Handler,
		},
		{
			MethodName: "GetDeviceStatus",
			Handler:    _OrchestratorService_GetDeviceStatus_Handler,
		},
		{
			MethodName: "RunAITask",
			Handler:    _OrchestratorService_RunAITask_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _OrchestratorService_HealthCheck_Handler,
		},
		{
			MethodName: "ExecuteRoutedCommand",
			Handler:    _OrchestratorService_ExecuteRoutedCommand_Handler,
		},
		{
			MethodName: "SubmitJob",
			Handler:    _OrchestratorService_SubmitJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _OrchestratorService_GetJob_Handler,
		},
		{
			MethodName: "RunTask",
			Handler:    _OrchestratorService_RunTask_Handler,
		},
		{
			MethodName: "PreviewPlan",
			Handler:    _OrchestratorService_PreviewPlan_Handler,
		},
		{
			MethodName: "PreviewPlanCost",
			Handler:    _OrchestratorService_PreviewPlanCost_Handler,
		},
		{
			MethodName: "StartWebRTC",
			Handler:    _OrchestratorService_StartWebRTC_Handler,
		},
		{
			MethodName: "CompleteWebRTC",
			Handler:    _OrchestratorService_CompleteWebRTC_Handler,
		},
		{
			MethodName: "StopWebRTC",
			Handler:    _OrchestratorService_StopWebRTC_Handler,
		},
		{
			MethodName: "CreateDownloadTicket",
			Handler:    _OrchestratorService_CreateDownloadTicket_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _OrchestratorService_ReadFile_Handler,
		},
		{
			MethodName: "SyncChatMemory",
			Handler:    _OrchestratorService_SyncChatMemory_Handler,
		},
		{
			MethodName: "GetChatMemory",
			Handler:    _OrchestratorService_GetChatMemory_Handler,
		},
		{
			MethodName: "RunLLMTask",
			Handler:    _OrchestratorService_RunLLMTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator.proto",
}
